{% set name = "tempo2" %}
{% set version = "2023.05.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # for "Download" versions use:
  url: "https://bitbucket.org/psrsoft/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz"
  # for versions that don't exist in "Download" but are tagged use:
  #url: https://bitbucket.org/psrsoft/{{ name }}/get/{{ version }}.tar.gz
  # for versions based on an untagged git hash (required for v2021.07.1) use:
  #url: https://bitbucket.org/psrsoft/{{ name }}/get/e6fb8ca69895.tar.gz
  sha256: c5a8ecd28cfa2c8914185e3af16cd33a028b2e5d5e9c31388892bc19fa123e8e

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - autoconf
    - automake
    - libtool
    - make      # [unix]
  host:
    - cfitsio
    - pgplot
    - gsl
    - fftw
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
  run:
    - cfitsio
    - pgplot
    - gsl
    - fftw
    - libblas
    - liblapack
    - llvm-openmp  # [osx]

test:
  source_files:
    - tests/test_data/test_de430.par
    - tests/test_data/test_de430.tim
  commands:
    - tempo2 -f tests/test_data/test_de430.par tests/test_data/test_de430.tim

about:
  home: https://bitbucket.org/psrsoft/tempo2/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Tempo2 is a high precision pulsar timing tool. Tempo2 is not tempo3 either.
  dev_url: https://bitbucket.org/psrsoft/tempo2/

extra:
  recipe-maintainers:
    - demorest
    - sixbynine
    - mattpitkin
