{% set name = "tempo2" %}
{% set version = "2020.11.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # eg, https://bitbucket.org/psrsoft/tempo2/downloads/tempo2-2020.11.1.tar.gz
  url: "https://bitbucket.org/psrsoft/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz"
  sha256: 4351703c7c347f0e238d859d77350e5d07826669257a550873f7386942ae5ba3
  # example of how to get untagged git hash version
  ## This is v2020.07.1 but not tagged
  #url: https://bitbucket.org/psrsoft/{{ name }}/get/b054862c0788.tar.gz
        
build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - autoconf
    - automake
    - libtool
  host:
    - cfitsio
    - pgplot
    - gsl
    - fftw
    - libblas
    - libcblas
    - liblapack
    - mkl
    - llvm-openmp
  run:
    - cfitsio
    - pgplot
    - gsl
    - fftw
    - libblas
    - libcblas
    - liblapack
    - mkl
    - llvm-openmp

test:
  source_files:
    - tests/test_data/test_de430.par
    - tests/test_data/test_de430.tim
  commands:
    - tempo2 -f tests/test_data/test_de430.par tests/test_data/test_de430.tim

about:
  home: https://bitbucket.org/psrsoft/tempo2/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Tempo2 is a high precision pulsar timing tool. Tempo2 is not tempo3 either.
  dev_url: https://bitbucket.org/psrsoft/tempo2/

extra:
  recipe-maintainers:
    - demorest
    - sixbynine
    - mattpitkin
